# Generated by Django 5.2.8 on 2025-12-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_transactions", models.IntegerField(default=0)),
                (
                    "average_transaction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cash_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "card_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "mobile_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "insurance_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("medicines_sold", models.IntegerField(default=0)),
                ("total_units_sold", models.IntegerField(default=0)),
                ("new_customers", models.IntegerField(default=0)),
                ("returning_customers", models.IntegerField(default=0)),
                (
                    "cost_of_goods_sold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gross_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("staff_sales", models.JSONField(default=dict)),
                ("low_stock_alerts", models.IntegerField(default=0)),
                ("expiry_alerts", models.IntegerField(default=0)),
                ("out_of_stock_items", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "daily_summaries",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="daily_summa_date_4d8318_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthlySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_transactions", models.IntegerField(default=0)),
                (
                    "average_daily_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sales_growth_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("top_selling_products", models.JSONField(default=list)),
                ("new_customers", models.IntegerField(default=0)),
                ("total_active_customers", models.IntegerField(default=0)),
                (
                    "customer_retention_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_cogs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gross_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_inventory_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stock_turnover_ratio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_returns",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "return_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "monthly_summaries",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="monthly_sum_year_4b3259_idx"
                    )
                ],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("sales_growth", "Sales Growth"),
                            ("profit_margin", "Profit Margin"),
                            ("inventory_turnover", "Inventory Turnover"),
                            ("customer_acquisition", "Customer Acquisition"),
                            ("customer_retention", "Customer Retention"),
                            ("average_transaction", "Average Transaction Value"),
                            ("stock_accuracy", "Stock Accuracy"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_target_met", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "performance_metrics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "date"],
                        name="performance_metric__72ccc8_idx",
                    )
                ],
                "unique_together": {("metric_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Report"),
                            ("inventory", "Inventory Report"),
                            ("profit_loss", "Profit & Loss Report"),
                            ("customer", "Customer Report"),
                            ("stock_movement", "Stock Movement Report"),
                            ("expiry", "Expiry Report"),
                            ("low_stock", "Low Stock Report"),
                            ("daily_summary", "Daily Summary"),
                            ("monthly_summary", "Monthly Summary"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(
                        blank=True, help_text="Comma-separated email addresses"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("next_run", models.DateTimeField()),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("export_format", models.CharField(default="pdf", max_length=10)),
                ("include_charts", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="scheduled_reports", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "report_schedules",
                "ordering": ["next_run"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Report"),
                            ("inventory", "Inventory Report"),
                            ("profit_loss", "Profit & Loss Report"),
                            ("customer", "Customer Report"),
                            ("stock_movement", "Stock Movement Report"),
                            ("expiry", "Expiry Report"),
                            ("low_stock", "Low Stock Report"),
                            ("daily_summary", "Daily Summary"),
                            ("monthly_summary", "Monthly Summary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("fields", models.JSONField(help_text="Fields to include in report")),
                (
                    "filters",
                    models.JSONField(
                        blank=True, help_text="Default filters", null=True
                    ),
                ),
                (
                    "grouping",
                    models.JSONField(
                        blank=True, help_text="Grouping configuration", null=True
                    ),
                ),
                (
                    "header_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="report_templates/"
                    ),
                ),
                ("footer_text", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Report"),
                            ("inventory", "Inventory Report"),
                            ("profit_loss", "Profit & Loss Report"),
                            ("customer", "Customer Report"),
                            ("stock_movement", "Stock Movement Report"),
                            ("expiry", "Expiry Report"),
                            ("low_stock", "Low Stock Report"),
                            ("daily_summary", "Daily Summary"),
                            ("monthly_summary", "Monthly Summary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("report_data", models.JSONField()),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("file_format", models.CharField(blank=True, max_length=10)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_reports",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type"], name="saved_repor_report__155f6c_idx"
                    ),
                    models.Index(
                        fields=["generated_at"], name="saved_repor_generat_80edeb_idx"
                    ),
                ],
            },
        ),
    ]
