# Generated by Django 5.2.8 on 2025-12-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medicines",
                to="inventory.category",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medicines_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="inventory.medicine",
            ),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="adjusted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.batch",
            ),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjustments",
                to="inventory.medicine",
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(fields=["sku"], name="medicines_sku_bc0587_idx"),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(fields=["barcode"], name="medicines_barcode_95be03_idx"),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(fields=["name"], name="medicines_name_017048_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together={("medicine", "batch_number")},
        ),
    ]
