# Generated by Django 5.2.8 on 2025-12-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
                ("license_number", models.CharField(max_length=100, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("hospital_clinic", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "doctors",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prescription_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("prescription_date", models.DateField()),
                ("valid_until", models.DateField()),
                ("diagnosis", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Special instructions or notes"
                    ),
                ),
                (
                    "prescription_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="prescriptions/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partially Filled"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="customers.customer",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="prescriptions.doctor",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filled_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prescriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosage", models.CharField(help_text="e.g., 500mg", max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        help_text="e.g., Twice daily, Every 8 hours", max_length=100
                    ),
                ),
                (
                    "duration",
                    models.CharField(help_text="e.g., 7 days, 2 weeks", max_length=100),
                ),
                ("quantity_prescribed", models.IntegerField()),
                ("quantity_dispensed", models.IntegerField(default=0)),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Special instructions for this medicine"
                    ),
                ),
                ("is_filled", models.BooleanField(default=False)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.medicine",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
            options={
                "db_table": "prescription_items",
            },
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["prescription_number"], name="prescriptio_prescri_b8a9ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["prescription_date"], name="prescriptio_prescri_4a4146_idx"
            ),
        ),
    ]
