# Generated by Django 5.2.8 on 2025-12-06 18:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("alternate_phone", models.CharField(blank=True, max_length=15)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("address_line1", models.CharField(max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="Kenya", max_length=100)),
                (
                    "allergies",
                    models.TextField(blank=True, help_text="Known drug allergies"),
                ),
                ("medical_conditions", models.TextField(blank=True)),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                (
                    "customer_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("loyalty_points", models.IntegerField(default=0)),
                (
                    "total_purchases",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer_id"], name="customers_custome_b85ebb_idx"
                    ),
                    models.Index(fields=["phone"], name="customers_phone_91048b_idx"),
                    models.Index(fields=["email"], name="customers_email_92e882_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurance_company", models.CharField(max_length=200)),
                ("policy_number", models.CharField(max_length=100, unique=True)),
                ("group_number", models.CharField(blank=True, max_length=100)),
                (
                    "coverage_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurances",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Customer Insurance",
                "db_table": "customer_insurance",
                "ordering": ["-valid_until"],
            },
        ),
    ]
